name: Checkstyle

on:
  pull_request:

permissions:
  contents: read

jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        if: always()
        with:
          github_token: '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'
          reporter: 'github-pr-check'
          tool_name: 'reviewdog'
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'
          level: error
